# Generated by Django 3.2.13 on 2022-05-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='number', max_length=1000)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.CharField(default='body', max_length=1000),
        ),
    ]
